version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.0
    - 1.4.0
  - dependency-name: minitest
    versions:
    - 5.14.3
  - dependency-name: jwt
    versions:
    - 2.2.2
